# Generated by Django 3.1.7 on 2021-03-25 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ColorProperty",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color_name",
                    models.CharField(max_length=100, verbose_name="Colorproperty name"),
                ),
                (
                    "rank",
                    models.IntegerField(
                        help_text="1 is very important, 1000 is not important",
                        verbose_name="Matter of importance",
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="Breeder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=60, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=60, verbose_name="Last name"),
                ),
                (
                    "breeding_reg_nr",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Breeding registration number",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Home address"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Phone number",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Remarks / Notes")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bird",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ring_number",
                    models.CharField(
                        help_text="This is to uniquely identify the bird and to determine its breeder",
                        max_length=20,
                        verbose_name="Ring number",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("male", "Male"),
                            ("female", "Female"),
                        ],
                        default="unknown",
                        max_length=10,
                        verbose_name="Sex",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("18.001.001", "Light Green"),
                            ("18.002.001", "Dark Green"),
                            ("18.002.002", "Olive Green"),
                            ("18.002.003", "Grey Green"),
                            ("18.002.004", "Violet Green"),
                            ("18.004.001", "Sky Blue"),
                            ("18.004.002", "Mauve"),
                            ("18.004.003", "Gray"),
                            ("18.004.004", "Violet Blue"),
                            ("18.004.005", "Violet Blue"),
                        ],
                        max_length=15,
                        verbose_name="Color",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of birth"
                    ),
                ),
                (
                    "date_of_death",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of death"
                    ),
                ),
                (
                    "is_owned",
                    models.BooleanField(default=False, verbose_name="I own this bird"),
                ),
                (
                    "is_for_sale",
                    models.BooleanField(
                        default=False, verbose_name="This bird is for sale"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Remarks / Notes")),
                (
                    "photo",
                    models.ImageField(
                        default="assets/budgie-silhouette.png",
                        upload_to="assets/uploads/bird_pics",
                    ),
                ),
                (
                    "breeder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="breeder",
                        to="budgie_bird.breeder",
                    ),
                ),
                (
                    "color_property",
                    models.ManyToManyField(
                        related_name="color_properties",
                        to="budgie_bird.ColorProperty",
                        verbose_name="Color properties",
                    ),
                ),
                (
                    "father",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ancestor_father",
                        to="budgie_bird.bird",
                        verbose_name="Father",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ancestor_mother",
                        to="budgie_bird.bird",
                        verbose_name="Mother",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owner",
                        to="budgie_bird.breeder",
                    ),
                ),
                (
                    "split_property",
                    models.ManyToManyField(
                        related_name="split_properties",
                        to="budgie_bird.ColorProperty",
                        verbose_name="Split properties",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["ring_number"],
                "unique_together": {("user", "ring_number")},
            },
        ),
    ]
