# Generated by Django 3.1.7 on 2021-03-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgie_bird", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bird",
            name="sex",
        ),
        migrations.AddField(
            model_name="bird",
            name="gender",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("male", "Male"),
                    ("female", "Female"),
                ],
                default="unknown",
                max_length=10,
                verbose_name="Sex",
            ),
        ),
        migrations.AlterField(
            model_name="bird",
            name="color",
            field=models.CharField(
                choices=[
                    ("18.001.001", "Light Green"),
                    ("18.002.001", "Dark Green"),
                    ("18.002.002", "Olive Green"),
                    ("18.002.003", "Grey Green"),
                    ("18.002.004", "Violet Green"),
                    ("18.004.001", "Sky Blue"),
                    ("18.004.002", "Mauve"),
                    ("18.004.003", "Gray"),
                    ("18.004.004", "Violet Blue"),
                    ("18.004.005", "Violet Blue"),
                ],
                max_length=15,
                verbose_name="Color",
            ),
        ),
        migrations.AlterField(
            model_name="bird",
            name="photo",
            field=models.ImageField(
                default="bird_pics/default.jpg", upload_to="bird_pics"
            ),
        ),
        migrations.AlterField(
            model_name="bird",
            name="ring_number",
            field=models.CharField(
                help_text="This is to uniquely identify the bird and to determine its breeder",
                max_length=20,
                unique=True,
                verbose_name="Ring number",
            ),
        ),
    ]
