# Generated by Django 3.1.7 on 2021-03-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgie_bird", "0002_auto_20210325_1350"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bird",
            name="photo",
            field=models.ImageField(
                default="assets/budgie-silhouette.png",
                upload_to="assets/uploads/bird_pics",
            ),
        ),
    ]
