# Generated by Django 3.1.7 on 2021-03-27 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budgie_bird", "0002_allow_blank_properties"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bird",
            options={
                "ordering": ["ring_number"],
                "verbose_name": "Bird",
                "verbose_name_plural": "Birds",
            },
        ),
        migrations.AlterModelOptions(
            name="breeder",
            options={
                "ordering": [django.db.models.functions.text.Lower("last_name")],
                "verbose_name": "Breeder",
                "verbose_name_plural": "Breeders",
            },
        ),
        migrations.AlterModelOptions(
            name="colorproperty",
            options={
                "ordering": ["rank"],
                "verbose_name": "Color property",
                "verbose_name_plural": "Color properties",
            },
        ),
        migrations.AddField(
            model_name="colorproperty",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="budgie_user.budgieuser",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bird",
            name="breeder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="breeder",
                to="budgie_bird.breeder",
            ),
        ),
        migrations.AlterField(
            model_name="bird",
            name="color",
            field=models.CharField(
                choices=[
                    ("18.001.001", "Light Green"),
                    ("18.002.001", "Dark Green"),
                    ("18.002.002", "Olive Green"),
                    ("18.002.003", "Grey Green"),
                    ("18.002.004", "Violet Green"),
                    ("18.004.001", "Sky Blue"),
                    ("18.004.002", "Mauve"),
                    ("18.004.003", "Gray"),
                    ("18.004.004", "Violet Grey"),
                    ("18.004.005", "Violet Blue"),
                ],
                max_length=15,
                verbose_name="Color",
            ),
        ),
        migrations.AlterField(
            model_name="bird",
            name="father",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ancestor_father",
                to="budgie_bird.bird",
                verbose_name="Vader",
            ),
        ),
        migrations.AlterField(
            model_name="bird",
            name="is_owned",
            field=models.BooleanField(
                default=False,
                help_text="Sometimes when you are the owner, the bird is not at your disposal due to a trade",
                verbose_name="I own this bird",
            ),
        ),
        migrations.AlterField(
            model_name="bird",
            name="mother",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ancestor_mother",
                to="budgie_bird.bird",
                verbose_name="Moeder",
            ),
        ),
        migrations.AlterField(
            model_name="bird",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner",
                to="budgie_bird.breeder",
            ),
        ),
    ]
