# Generated by Django 4.1 on 2022-09-02 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("budgie_bird", "0003_add_user_to_color_properties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bird",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner",
                to="budgie_bird.breeder",
                verbose_name="Owner",
            ),
        ),
    ]
