# Generated by Django 4.1 on 2022-09-16 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("budgie_bird", "0004_alter_bird_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bird",
            name="father",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("gender", "male"), ("gender", "unknown"), _connector="OR"
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ancestor_father",
                to="budgie_bird.bird",
                verbose_name="Vader",
            ),
        ),
        migrations.AlterField(
            model_name="bird",
            name="mother",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("gender", "female"), ("gender", "unknown"), _connector="OR"
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ancestor_mother",
                to="budgie_bird.bird",
                verbose_name="Moeder",
            ),
        ),
        migrations.AlterField(
            model_name="bird",
            name="ring_number",
            field=models.CharField(
                help_text="This is to uniquely identify the bird and to determine its breeder",
                max_length=40,
                verbose_name="Ring number",
            ),
        ),
    ]
