# Generated by Django 4.1.5 on 2023-01-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgie_bird", "0006_alter_breeder_breeding_reg_nr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bird",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("18.001.001", "Light Green"),
                    ("18.002.001", "Dark Green"),
                    ("18.002.002", "Olive Green"),
                    ("18.002.003", "Grey Green"),
                    ("18.002.004", "Violet Green"),
                    ("18.004.001", "Sky Blue"),
                    ("18.004.002", "Cobalt Blue"),
                    ("18.004.003", "Mauve"),
                    ("18.004.004", "Gray"),
                    ("18.004.005", "Violet Blue"),
                ],
                max_length=15,
                verbose_name="Color",
            ),
        ),
    ]
