# Generated by Django 4.2.1 on 2023-12-15 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("budgie_bird", "0007_alter_bird_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="BirdProxy",
            fields=[],
            options={
                "verbose_name": "Bird",
                "verbose_name_plural": "Birds",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("budgie_bird.bird",),
        ),
        migrations.AlterField(
            model_name="bird",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("18.001.001", "Light Green"),
                    ("18.002.001", "Dark Green"),
                    ("18.002.002", "Olive Green"),
                    ("18.002.003", "Grey Green"),
                    ("18.002.004", "Violet Green"),
                    ("18.004.001", "Sky Blue"),
                    ("18.004.002", "Cobalt Blue"),
                    ("18.004.003", "Mauve"),
                    ("18.004.004", "Gray"),
                    ("18.004.005", "Violet Blue"),
                    ("00.000.000", "Unknown"),
                ],
                max_length=15,
                verbose_name="Color",
            ),
        ),
        migrations.AlterField(
            model_name="bird",
            name="father",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("gender", "male"), ("gender", "unknown"), _connector="OR"
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ancestor_father",
                to="budgie_bird.bird",
                verbose_name="Father",
            ),
        ),
        migrations.AlterField(
            model_name="bird",
            name="mother",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("gender", "female"), ("gender", "unknown"), _connector="OR"
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ancestor_mother",
                to="budgie_bird.bird",
                verbose_name="Mother",
            ),
        ),
    ]
