# Generated by Django 4.2.8 on 2024-01-01 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("budgie_bird", "0008_birdproxy_alter_bird_color_alter_bird_father_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="birdproxy",
            options={
                "verbose_name": "Niet in gebruik: Vogel",
                "verbose_name_plural": "Niet in gebruik: Vogels",
            },
        ),
        migrations.AlterField(
            model_name="bird",
            name="father",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("gender", "male"), ("gender", "unknown"), _connector="OR"
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ancestor_father",
                to="budgie_bird.bird",
                verbose_name="Vader",
            ),
        ),
        migrations.AlterField(
            model_name="bird",
            name="mother",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("gender", "female"), ("gender", "unknown"), _connector="OR"
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ancestor_mother",
                to="budgie_bird.bird",
                verbose_name="Moeder",
            ),
        ),
    ]
