# Generated by Django 5.0.4 on 2025-03-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "budgie_bird",
            "0010_birdphoto_squashed_0012_alter_birdphoto_options_alter_birdphoto_notes",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="birdphoto",
            options={
                "ordering": ["uploaded_at"],
                "verbose_name": "Additional bird photo",
                "verbose_name_plural": "Additional bird photos",
            },
        ),
    ]
