# Generated by Django 6.0.2 on 2026-08-07 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgie_bird', '0013_alter_birdphoto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description_0', models.CharField(max_length=255, verbose_name='Description for level 0')),
                ('description_1', models.CharField(max_length=255, verbose_name='Description for level 1')),
                ('description_2', models.CharField(max_length=255, verbose_name='Description for level 2')),
                ('description_3', models.CharField(max_length=255, verbose_name='Description for level 3')),
            ],
            options={
                'verbose_name': 'Bird characteristic',
                'verbose_name_plural': 'Bird characteristics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BirdCharacteristicSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_grade', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='Selected grade')),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_selections', to='budgie_bird.bird')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bird_selections', to='budgie_bird.birdcharacteristic', verbose_name='Characteristic')),
            ],
            options={
                'verbose_name': 'Bird characteristic selection',
                'verbose_name_plural': 'Bird characteristic selections',
                'constraints': [models.UniqueConstraint(fields=('bird', 'characteristic'), name='unique_bird_characteristic')],
            },
        ),
    ]
