# Generated by Django 4.1 on 2022-09-02 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgie_breeding", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="breedingcouple",
            options={
                "verbose_name": "Breeding couple",
                "verbose_name_plural": "Breeding couples",
            },
        ),
        migrations.AlterModelOptions(
            name="breedingseason",
            options={
                "ordering": ["-starting_year", "-starting_month"],
                "verbose_name": "Breeding season",
                "verbose_name_plural": "Breeding seasons",
            },
        ),
        migrations.AlterModelOptions(
            name="egg",
            options={"verbose_name": "Egg", "verbose_name_plural": "Eggs"},
        ),
        migrations.RemoveField(
            model_name="breedingseason",
            name="month",
        ),
        migrations.RemoveField(
            model_name="breedingseason",
            name="year",
        ),
        migrations.AddField(
            model_name="breedingseason",
            name="starting_month",
            field=models.CharField(
                choices=[
                    ("1", "januari"),
                    ("2", "februari"),
                    ("3", "march"),
                    ("4", "april"),
                    ("5", "may"),
                    ("6", "june"),
                    ("7", "july"),
                    ("8", "august"),
                    ("9", "september"),
                    ("10", "october"),
                    ("11", "november"),
                    ("12", "december"),
                ],
                default="1",
                help_text="This allows you to distinguish breeding rounds if you have multiple per year",
                max_length=15,
                verbose_name="Starting month",
            ),
        ),
        migrations.AddField(
            model_name="breedingseason",
            name="starting_year",
            field=models.IntegerField(
                default=2022,
                validators=[
                    django.core.validators.MaxValueValidator(2100),
                    django.core.validators.MinValueValidator(2000),
                ],
                verbose_name="Starting year",
            ),
        ),
    ]
