# Generated by Django 4.1 on 2022-09-11 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("budgie_breeding", "0003_alter_breedingcouple_female_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="egg",
            name="couple",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="budgie_breeding.breedingcouple",
                verbose_name="Breeding couple",
            ),
        ),
    ]
