# Generated by Django 4.1 on 2022-10-02 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budgie_breeding", "0005_alter_breedingcouple_female_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Locations",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="A code to represent the location of this cage",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Description")),
                (
                    "current_breeding_couple",
                    models.ForeignKey(
                        blank=True,
                        help_text="This is the couple that is currently breeding here, can also be empty",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="budgie_breeding.breedingcouple",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
