# Generated by Django 4.1 on 2022-10-02 08:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budgie_breeding", "0006_locations"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Locations",
            new_name="Location",
        ),
    ]
