# Generated by Django 4.1 on 2022-10-02 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("budgie_breeding", "0007_rename_locations_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={
                "verbose_name": "Location / Cage",
                "verbose_name_plural": "Locations / Cages",
            },
        ),
        migrations.AddField(
            model_name="breedingcouple",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="budgie_breeding.location",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="current_breeding_couple",
            field=models.ForeignKey(
                blank=True,
                help_text="This is the couple that is currently breeding here, can also be empty",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_couple",
                to="budgie_breeding.breedingcouple",
            ),
        ),
    ]
