# Generated by Django 4.1 on 2022-10-02 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "budgie_breeding",
            "0008_alter_location_options_breedingcouple_location_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="breedingcouple",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="budgie_breeding.location",
                verbose_name="Location / Cage",
            ),
        ),
    ]
