# Generated by Django 4.1.5 on 2023-01-29 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("budgie_bird", "0007_alter_bird_color"),
        ("budgie_breeding", "0010_alter_location_current_breeding_couple"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breedingcouple",
            name="female",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("gender", "female"), ("is_owned", True)),
                    models.Q(("gender", "unknown"), ("is_owned", True)),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="female",
                to="budgie_bird.bird",
                verbose_name="Female",
            ),
        ),
        migrations.AlterField(
            model_name="breedingcouple",
            name="male",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("gender", "male"), ("is_owned", True)),
                    models.Q(("gender", "unknown"), ("is_owned", True)),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="male",
                to="budgie_bird.bird",
                verbose_name="Male",
            ),
        ),
    ]
