# Generated by Django 4.2.10 on 2024-02-14 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("budgie_breeding", "0011_alter_breedingcouple_female_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="egg",
            name="couple",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eggs",
                to="budgie_breeding.breedingcouple",
                verbose_name="Breeding couple",
            ),
        ),
    ]
