# Generated by Django 5.0.4 on 2024-04-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgie_breeding", "0012_alter_egg_couple"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breedingseason",
            name="starting_month",
            field=models.CharField(
                choices=[
                    ("JAN", "January"),
                    ("FEB", "February"),
                    ("MAR", "March"),
                    ("APR", "April"),
                    ("MAY", "May"),
                    ("JUN", "June"),
                    ("JUL", "July"),
                    ("AUG", "August"),
                    ("SEP", "September"),
                    ("OCT", "October"),
                    ("NOV", "November"),
                    ("DEC", "December"),
                ],
                default="JAN",
                help_text="This allows you to distinguish breeding rounds if you have multiple per year",
                max_length=15,
                verbose_name="Starting month",
            ),
        ),
    ]
