# Generated by Django 4.1 on 2022-08-20 14:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "import_file",
                    models.FileField(
                        help_text="Upload an Excel file (.xlsx or .csv) to import new birds or update them",
                        upload_to="",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["csv", "xlsx"]
                            )
                        ],
                        verbose_name="Import file",
                    ),
                ),
                (
                    "uploaded_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Upload date"),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False, verbose_name="Completed successfully"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="This field contains information about the import process, when something special happens on import",
                        null=True,
                        verbose_name="Notes after import",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
