# Generated by Django 4.1 on 2022-09-02 00:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budgie_import", "0001_importfile_import_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importfile",
            options={
                "ordering": ["uploaded_date"],
                "verbose_name": "Import file",
                "verbose_name_plural": "Import files",
            },
        ),
        migrations.AlterField(
            model_name="importfile",
            name="import_file",
            field=models.FileField(
                help_text="Upload an Excel file (.xlsx or .csv) to import new birds or update them",
                upload_to="assets/uploads/import",
                validators=[
                    django.core.validators.FileExtensionValidator(["csv", "xlsx"])
                ],
                verbose_name="Import file",
            ),
        ),
        migrations.AlterField(
            model_name="importfile",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
