# name of our workflow
name: pyBudgie CI

# triggers for our workflow
on:
  # opening a pull request to master and develop branch will be a trigger
  pull_request:
    branches:
      - develop
      - master
  # any code pushed to master and develop branch will also be a trigger
  push:
    branches:
      - master
      - develop


jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: pybudgie__test
    steps:
      - name: Checkout code # checking our the code at current commit that triggers the workflow
        uses: actions/checkout@v3
      - name: Cache dependency # caching dependency will make our build faster.
        uses: actions/cache@v3 # for more info checkout pip section documentation at https://github.com/actions/cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Setup python environment # setting python environment to 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install gettext (dependency for locale generation)
        run: sudo apt-get -y install gettext
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install dev requirements
        run: pip install -r requirements-dev.txt
      - name: Check Syntax with PyLama
        run: pylama
      - name: Generate locales
        run: python manage.py compilemessages --settings=pybudgie.config.settings_ci
      - name: Run Migrations
        run: python manage.py migrate --settings=pybudgie.config.settings_ci
      - name: Run Test with coverage
        run: coverage run ./manage.py test --settings=pybudgie.config.settings_ci
      - name: Generate coverage
        run: coverage json
      - name: Update Coverage badge
        uses: jeroenpeters1986/coverage-badge-action@main